#!/bin/sh

# Simplified preinst script with Dopamine 2 compatibility

# Detect jailbreak type
if [ -d "/var/jb" ]; then
    JBPREFIX="/var/jb"
    launchctl bootout system /var/jb/Library/LaunchDaemons/wangmc.projectx.plist
else
    JBPREFIX=""
    launchctl bootout system /Library/LaunchDaemons/wangmc.projectx.plist
fi



exit 0 